import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
/** custom styles */
import '../styles/globals.css';
import '../styles/grid.css';
/** components */
import Header from '@/components/layout/header';

const font = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
